_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

accelerator: auto
devices: auto
strategy: auto
num_nodes: 1
# mixed precision for extra speed-up
precision: 32-true
deterministic: False

profiler: simple

fast_dev_run: False
log_every_n_steps: 1
