# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: ${oc.env:PROJECT_ROOT}

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}
config_tree: ${paths.output_dir}
# path to working directory
work_dir: ${hydra:runtime.cwd}

# CHANGE HERE

# where you want to save your experiments
# in configs/experiment/aaai/ we will call ${paths.images_dir}/NAME_OF_EXPERIMENT
images_dir: ${paths.root_dir}/experiments
# where the models are saved
model_dir: ${paths.root_dir}/data_models

# path to data directory, where datasets are stored
dataset_dir: Paulgrimal

# path to logging directory, where logs are stored
log_dir: ${paths.root_dir}/logs
